# Texas Instruments SK-AM62A-LP board
BOARD_NAME="SK-AM62A-LP"
BOARD_VENDOR="ti"
BOARDFAMILY="k3"
BOOT_SOC="am62a"
BOOTCONFIG="sk_am62a_lp_a53_defconfig"
TIBOOT3_BOOTCONFIG="am62ax_evm_r5_defconfig"
TIBOOT3_FILE="tiboot3.bin"
BOOTFS_TYPE="fat"
BOOT_FDT_FILE="ti/k3-am62a7-sk-lp.dtb"
KERNELCONFIG="defconfig"
BOOT_USE_BLOBS=yes
BOOT_BLOB_DIR="ti/am62a"
BOOTSCRIPT="boot-k3-sk-am62a-lp.cmd:boot.cmd"
KERNEL_TARGET="vendor,vendor-rt,vendor-edge,edge"
DEFAULT_CONSOLE="serial"
SERIALCON="ttyS2"
MODULES_BLACKLIST=""
KERNEL_MAJOR_MINOR="6.18"
ATF_PLAT="k3"
ATF_BOARD="lite"
OPTEE_ARGS="CFG_TEE_CORE_LOG_LEVEL=1"
OPTEE_PLATFORM="k3-am62x"

function post_family_tweaks_bsp__sk_am62a_lp_remove_sysctl_conflict() {
    display_alert "Removing conflicting sysctl file" "${BOARD}" "info"
    rm -f "${destination}/usr/lib/sysctl.d/50-default.conf"
}
